# Imagen basada en otra imagen, desde, linux preinstalado con node
FROM node:18-alpine3.15

# Set working directory
# Establecer un working directory
# Crear una carpeta fisicamente
RUN mkdir -p /var/www/pokedex
WORKDIR /var/www/pokedex

# Copiar el directorio y su contenido
# Copiar todo de la app (origen, destino), pegar al working directory
COPY . ./var/www/pokedex
COPY package.json tsconfig.json tsconfig.build.json /var/www/pokedex/
# instale todas las dependencias de produccion
RUN yarn install --prod
RUN yarn build


# Dar permiso para ejecutar la applicación
# Se crea un nuevo usuario, permiso a ese directorio
RUN adduser --disabled-password pokeuser
RUN chown -R pokeuser:pokeuser /var/www/pokedex
USER pokeuser

# Limpiar el caché
RUN yarn cache clean --force

EXPOSE 3000

CMD [ "yarn","start" ]